apiVersion: apps/v1
kind: Deployment
metadata:
  name: webscraper-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webscraper-mongo
  template:
    metadata:
      labels:
        app: webscraper-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webscraper-mongo
spec:
  ports:
  - port: 27017
  selector:
    app: webscraper-mongo
